name: example_cli
description: A dialog asking the same questions as ng new when creating a new workspace/project
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cli_dialog:
  dart_console: ^1.0.0

dev_dependencies:
  test: ^1.16.5

dependency_overrides:
  cli_dialog:
    path: ../
