name: cli_dialog
description: Create beautiful and powerful CLI prompts in Inquirer.js style and test them.
version: 0.5.0-dev
homepage: https://github.com/leonardoInf/cli_dialog

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_console: ^1.1.0-pre.1

dev_dependencies:
  test_coverage: ^0.4.3
  coveralls: ^5.2.0
  test: ^1.16.5
  pedantic: ^1.11.0
